export const LOAD_DAYS = 'LOAD_DAYS'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const REMOVE_SUBJECT = 'REMOVE_SUBJECT'
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'

export const LOAD_ATTENDANCE = 'LOAD_ATTENDANCE'
export const ADD_ATTENDANCE = 'ADD_ATTENDANCE'
export const REMOVE_ATTENDANCE = 'REMOVE_ATTENDANCE'
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE'

export const ADD_LATENESS = 'ADD_LATENESS'

export const INCREASE_PROGRESS = 'INCREASE_PROGRESS'
export const DECREASE_PROGRESS = 'DECREASE_PROGRESS'

export const INCREASE_LATENESS_PROGRESS = 'INCREASE_LATENESS_PROGRESS'
export const DECREASE_LATENESS_PROGRESS = 'DECREASE_LATENESS_PROGRESS'

export const CHANGE_AMOUNT_ABSENSES = 'CHANGE_AMOUNT_ABSENSES'
export const CHANGE_AMOUNT_LATENESS = 'CHANGE_AMOUNT_LATENESS'

export const CHANGE_AMOUNT = 'CHANGE_AMOUNT'

export const LOAD_PEOPLE = 'LOAD_PEOPLE'
export const ADD_PERSON = 'ADD_PERSON'
export const REMOVE_PERSON = 'REMOVE_PERSON'

export const LOAD_HOME_WORKS = 'LOAD_HOME_WORKS'
export const ADD_HOME_WORKS = 'ADD_HOME_WORKS'
export const REMOVE_HOME_WORKS = 'REMOVE_HOME_WORKS'
export const DO_COMPLETED_HOME_WORK = 'DO_COMPLETED_HOME_WORK'

export const ADD_GRADE = 'ADD_GRADE'
export const REMOVE_GRADE = 'REMOVE_GRADE'
export const EDIT_GRADE = 'EDIT_GRADE'

export const ADD_STUDY_SUBJECT = 'ADD_STUDY_SUBJECT'
export const REMOVE_STUDY_SUBJECT = 'REMOVE_STUDY_SUBJECT'
export const EDIT_STUDY_SUBJECT = 'EDIT_STUDY_SUBJECT'

export const ADD_GRADE_TO_SUBJECT = 'ADD_GRADE_TO_SUBJECT'
export const REMOVE_GRADE_FROM_SUBJECT = 'REMOVE_GRADE_FROM_SUBJECT'